openapi: 3.1.1
info:
  # TODO: Change Information
  title: Static File Service
  description: |
    This service allows storing and handling of static files
  version: 1.0.0
servers:
  - url: '/api/files/'
    description: WISdoM

  - url: 'http://localhost:8000'
    description: Development

components:
  # TODO: Remove if service won't handle private data
  securitySchemes:
    WISdoM:
      description: |
        Access Tokens issued by the User Management Service
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

security:
  - WISdoM: []


paths:
  /v1/public/{file}:
    get:
      security:
        - {}
      
      parameters:
        - in: path
          name: file
          description: the file that is to be retrieved
          required: true
          schema:
            type: string

      responses:
        "200":
          description: The requested file

  /v1/{bucket}/{basepath}:
    parameters:
      - in: path
        name: bucket
        description: name of the bucket the file should be uploaded to
        required: true
        schema:
          type: string
      - in: path
        name: basepath
        description: basepath under which the files are stored in the bucket
        required: true
        allowEmptyValue: true
        schema:
          type: string

    put:
      security:
        - WISdoM: ["static-files:write"]
      summary: Upload Files
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
  
  /v1/{bucket}/{file}:
    parameters:
        - in: path
          name: bucket
          description: name of the bucket the file should be uploaded to
          required: true
          schema:
            type: string
        - in: path
          name: file
          description: the file that is to be retrieved
          required: true
          schema:
            type: string
    
    get:
      security:
        - WISdoM: ["static-files:read"]
      
      responses:
        "200":
          description: The requested file


    delete:
      security:
        - WISdoM: ["static-files:delete"]
      
      responses:
        "204":
          description: File deleted



